name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker build -t playwright-script .
          docker run --rm playwright-script 2>&1

      - name: Send Slack message
        run: |
          curl -d "text=Build and test job completed for Build completed for repository: ${{ env.GITHUB_REPOSITORY }} : ${{ job.status }}" \
          -d "channel=C05DMJUHJCX" \
          -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
          -X POST https://slack.com/api/chat.postMessage
